tuirer/tuirer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import index




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),

    path('', include('tuites.urls')),
    path('', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tuirer/tuites/urls.py
from django.urls import path
from tuites.views import PostTuiteView

app_name = 'tuites'

urlpatterns = [
    path('postar/', PostTuiteView.as_view(), name='post_tuite'),
]

tuirer/users/urls.py
from django.urls import path
from users.views import ProfileView, ProfileEditView, UserLoginView, UserLogoutView

app_name = 'users'

urlpatterns = [
    path('perfil/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('perfil/<int:pk>/editar/', ProfileEditView.as_view(), name='profile-edit'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('login/', UserLogoutView.as_view(), name='logout'),
]

tuirer/superuser/models.py
from django.db import models

# Create your models here.

tuirer/tuites/models.py
from django.db import models

from tuites.managers import TuitesManager


class Tuite(models.Model):
    content = models.CharField('Tuite', max_length=280, default='Olá!')
    author = models.ForeignKey('users.User', verbose_name='Autor', on_delete=models.CASCADE, related_name='tuites')
    date_created = models.DateTimeField(auto_now_add=True)

    # objects = TuitesManager()

    def get_author_username(self):
        return self.author.username

    def __str__(self):
        return f'{self.author.username}: {self.content}'

    class Meta:
        ordering = ('content', )

tuirer/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    picture = models.ImageField('Fotode perfil', default='/img/blank-pic.png')
    following = models.ManyToManyField('self', blank=True)

tuirer/tuites/forms.py
from django import forms
from tuites.models import Tuite 


class PostTuiteForm(forms.ModelForm):
    class Meta:
        model = Tuite
        fields = ('content', 'author')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['author'].initial = self.initial['user'].id
        self.fields['author'].widget = forms.HiddenInput()
        self.fields['content'].help_text = 'Digite o que vc ta pensando'
        

    def clean(self):
        cleaned_data = super().clean()

        content = self.cleaned_data.get('content')
        if 'Temer' in content:
            raise forms.ValidationError('FORA TEMER')

        if not self.initial.get('user') == cleaned_data.get('author'):
            raise forms.ValidationError('Não tente burlar o sistema!')

        return cleaned_data

tuirer/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm


class UserSignupForm(UserCreationForm):
    pass

tuirer/core/views.py
from datetime import datetime

from django.http import HttpResponse
from django.shortcuts import render

from tuites.models import Tuite

from .helpers import get_character_name, ip_info

#from random import randint

# Create your views here.

def index(request):
    #nome = '<b>Farias</b>'
    #return HttpResponse(f'Sua pagina carregou {nome}.')
    #import ipdb; ipdb.set_trace() #breack-point 
    
    #id_random = randint(0,20)
    #print(id2)
    
    #nome = get_character_name(id_random)
    #return HttpResponse(f'Ola, tudo bem {nome}')
    
    # country = ip_info('country_name')
    # flag = ip_info('flag')
    # flag_image = f'<img src="{flag}" width=120" />'

    #return HttpResponse(
    #    f'Oi, como vai o <b>{country}</b>?<br>{flag_image}'
    #)

    context = {
        # 'my_name': 'Julia',
        # 'country_name': country,
        # 'flag_image': flag_image,
        'now': datetime.now(),
        'tuites': Tuite.objects.all(),
    }

    return render(request, 'home.html', context)

tuirer/superuser/views.py
from django.shortcuts import render

# Create your views here.

tuirer/tuites/views.py
from django.contrib import messages
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from tuites.forms import PostTuiteForm
from tuites.models import Tuite


class PostTuiteView(LoginRequiredMixin,CreateView):
    model = Tuite
    template_name = 'post_tuite.html'
    form_class = PostTuiteForm
    success_url = reverse_lazy('tuites:post_tuite')

    def get_initial(self):
        return {
            'user': self.request.user
        }

    def form_valid(self, form):
        messages.success(
            self.request,
            'Vc postou!'
        )
        return super().form_valid(form)



#LIXUUUU
# def post_tuite(request):
#     context = {}

#     if request.method == 'POST':
#         print('Enviando formulario!')
#         # print(request.POST)
#         content = request.POST.get('content', None)
#         if (content.isspace() or content == ''):
#             context['error'] = 'Tuite nao pode ta vaziu pow!'
#             return render(request, 'post_tuite.html', context)
#         # print(content)
#         # if (content.isspace() or content == ''):
#         #     context['certo'] = 'Valido, postando!'
#         #     return render(request, 'post_tuite.html', context)
#         else:
#             import ipdb; ipdb.set_trace()
#             Tuite.objects.create(
#                 content=content,
#                 author=request.user,
#             )
#             context['sucess_message'] = f'Seu Tuite: {tuite.content}, foi postado!'

#     return render(request, 'post_tuite.html', context)

tuirer/users/views.py
from django.views.generic import DetailView, UpdateView
from users.models import User
from django.urls import reverse_lazy
from users.mixins import ProfileAccessMixin
from django.contrib.auth.views import LoginView, LogoutView
from users.forms import UserSignupForm


class ProfileView(DetailView):
    model = User
    template_name = 'profile.html'
    context_object_name = 'profile'


class ProfileEditView(ProfileAccessMixin, UpdateView):
    model = User
    fields = ('picture', 'username')
    template_name = 'profile_edit.html'
    
    def get_success_url(self):
        return reverse_lazy('users:profile', args=[self.object.pk])


class UserLoginView(LoginView):
    template_name = 'login.html'
    redirect_authenticated_user = True



class UserLogoutView(LogoutView):
    pass


class UserSignupView(CreateView):
    model = User
    form_class =

tuirer/templates/base.html
{% load static %}

<html>
    <head>
        <title>Tuirer</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <!-- <style>
            body{
                background: #f0f0f0;
                font-family: sans-serif;
            }

            footer{
                background: orange;
            }
        </style> -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    </head>
    <body>
        <h2>Tuirer</h2>
        <!-- <p>{% lorem 1 p%}</p> -->
        <!-- <p>{{ user }}</p> -->
        {% include 'includes/menu.html' %}
        <p>
            <br>{{ now|date:"d \d\e F \d\e Y" }} <br> <br>
            
            <!-- {% if user.is_authenticated %}
                Olá, {{ user }}!
            {% else %}
                Saia daqui por favor.
            {% endif %} -->
            <!-- Meu nome é {{ my_name }}
            <br>
            Seu pais é {{ country_name }}
            <br>
            <img> {{ flag_image }}</p>img> -->
            
            <!-- <form>
                {% csrf_token %}
                <input type="text" name="name" placeholder="Nome">
                <input type="submit" value="Enviar">
            </form> -->
            {% block body %}
                Hello.
            {% endblock %}
        </p>
        <footer>
            {% block footer %}
                Esse é meu footer.
            {% endblock %}
        </footer>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>

tuirer/templates/home.html
{% extends 'base.html' %}

{% block body %}
    {% for tuite in tuites %}
            <div style="color: {% if forloop.first or forloop.last %}
                                    red
                                {% else %}
                                    blue
                                {% endif %}; 
                        border: 1px solid black;">    
                {{ tuite }}
            </div>
    {% endfor %}

{% endblock %}

tuirer/templates/includes/card.html
<div class="card">
    <p>{{ content }}</p>
    <p>autor: {{ author }}</p>
</div>

tuirer/templates/includes/cards.html
<div class="card">
    <p class="content">{{ tuite.content }}</p>
    <hr>
    <div class="author-and-likes">
        <a href="{% url 'profile' tuite.author.pk %}" class="author"> <!-- Adiciona link para o perfil do usuário -->
            <div class="author-avatar" style="background-image: url('{{ tuite.author.picture.url }}');"></div>
            {{ tuite.author }} 
        </a>
        <div class="likes">
            <i class="far fa-heart"></i>
            0
        </div>
    </div>
    </a>
</div>

tuirer/templates/includes/menu.html
<nav>
    <a href="{% url 'index' %}">Inicio</a>
    <a href="{% url 'tuites:post_tuite' %}">Postar tuite</a>
    {% if user.is_authenticate %}
        <a href="{% url 'users:profile' request.user.pk %}">Olá <b>{{ request.user.username }}</b></a>
        <a href="{% url 'users:logout' %}">Sair</a>
    {% else %}
        <a href="{% url 'users:login' %}">Entrar</a>
    {% endif %}
    

</nav>

tuirer/templates/login.html
{% extends 'base.html' %}

{% block body %}
    <a href="{% url 'users:profile' request.user.pk %}">Voltar para seu perfil</a>
    <form method="post" class="form-signin">
        {% csrf_token %}
        {{ form.as_p }}
        <!-- <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="">
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required="">
        <div class="checkbox mb-3">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <p class="mt-5 mb-3 text-muted">© 2017-2018</p> -->
      </form>
{% endblock %}

tuirer/templates/post_tuite.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block body %}

    {% if form.errors %}
        {% for error in form.non_field_errors %}
            <p class="error">{{ error }}</p>
        {% endfor %}
    {% endif %}
    
    {% if messages %}
        {% for messages in messages %}
            <p class="message">{{ messages }}</p>
        {% endfor %}
    {% endif %}
    
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            {% if not field.name == 'author' %}
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {% endif %}
            {% render_field field class="post-tuite-field" placeholder=field.label autofocus=True %}
            <p style="font-size: .8em; color: #666;">{{ field.help_text }}</p>
            {{ field.errors }}
        {% endfor %}
        <input type="submit" value="Postar Tuite">
    </form>
{% endblock %}

tuirer/templates/profile.html
{% extends 'base.html' %}

{% block body %}
    <div class="profile-picture" style="background-image: url('{{ profile.picture.url }}');"></div>

    {% if profile == request.user %}
        <a href="{% url 'tuites:profile-edit' request.user.pk %}">Editar perfil</a>
    {% endif %}

    {{ profile.email }}

    {{ profile.username }}

    {% for tuite in profile.tuite.all %}
        {% include 'includes/card.html' %}
    {% endfor %}
{% endblock %}

tuirer/templates/profile_edit.html
{% extends 'base.html' %}

{% block body %}
    <a href="{% url 'tuites:profile' request.user.pk %}">Voltar para seu perfil</a>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Enviar">
    </form>
{% endblock %}